<?
    define("OFFICE_PICKUP_DELIVERY", 45);
    define("PVZ_MSK_DELIVERY_FOR_CHEAP_ORDERS", 48);
    define("PVZ_MSK_DELIVERY_FOR_EXPENSIVE_ORDERS", 47);
    define("PVZ_SPB_DELIVERY_FOR_CHEAP_ORDERS", 50);
    define("PVZ_SPB_DELIVERY_FOR_EXPENSIVE_ORDERS", 51);
    define("INPOST_MSK_DELIVERY_FOR_CHEAP_ORDERS", 61);
    define("INPOST_MSK_DELIVERY_FOR_MEDIUM_ORDERS", 62);
    define("BOXBERRY_MSK_DELIVERY_FOR_CHEAP_ORDERS", 64);
    define("BOXBERRY_MSK_DELIVERY_FOR_MEDIUM_ORDERS", 66);
    define("INPOST_REGIONS_DELIVERY_FOR_CHEAP_ORDERS", 68);
    define("INPOST_REGIONS_DELIVERY_FOR_MEDIUM_ORDERS", 69);
    define("BOXBERRY_REGIONS_DELIVERY_FOR_CHEAP_ORDERS", 70);
    define("BOXBERRY_REGIONS_DELIVERY_FOR_MEDIUM_ORDERS", 71);
    define("INPOST_MSK_DELIVERY_FOR_EXPENSIVE_ORDERS", 72);
    define("BOXBERRY_MSK_DELIVERY_FOR_EXPENSIVE_ORDERS", 73);
    define("INPOST_REGIONS_DELIVERY_FOR_EXPENSIVE_ORDERS", 74);
    define("BOXBERRY_REGIONS_DELIVERY_FOR_EXPENSIVE_ORDERS", 76);
    define("ADDRESS_FIELD_PROPERTY", 45);

    CModule::IncludeModule("forum");

?>